In [8]:
import numpy as np


In [7]:
arr = []
#creates 3 random matrices with 3X3 dimensions

for i in range(3):
  arr.append(np.random.randint(-10,11, size=(3,3)))
print(arr)

[array([[-1,  7, -7],
       [ 9, -8, -6],
       [ 2,  4,  0]]), array([[-5, -4, -7],
       [ 3, -2, -7],
       [-7,  2, 10]]), array([[ 4, 10,  3],
       [-7, -8,  5],
       [ 9,  0,  0]])]


In [9]:
for j in arr:

  #calculates determinant
  det = np.linalg.det(j)

  print(f"Determinant: {det}")

  print()


  #determinant 0 does not have inverse
  if det == 0:
    print("Matrix is not invertible")
  else:

    #calculates inverse
    inv = np.linalg.inv(j)

    #matrix multpication between the array and inverse which gives identity matrix
    print(np.round(np.matmul(j, inv)) )

    print("\n"*2)






Determinant: -471.99999999999983

[[ 1. -0.  0.]
 [-0.  1. -0.]
 [-0.  0.  1.]]



Determinant: 9.99999999999998

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]



Determinant: 666.0000000000001

[[ 1. -0. -0.]
 [-0.  1. -0.]
 [ 0.  0.  1.]]



