In [1]:
import numpy as np


In [2]:
arr = []
#creates 3 random matrices with 3X3 dimensions

for i in range(3):
  arr.append(np.random.randint(-10,11, size=(3,3)))

In [6]:
for j in arr:

  #calculates determinant
  det = np.linalg.det(j)

  print(f"Determinant: {det}")

  print()


  #determinant 0 does not have inverse
  if det == 0:
    print("Matrix is not invertible")
  else:

    #calculates inverse
    inv = np.linalg.inv(j)

    #matrix multpication between the array and inverse which gives identity matrix
    print(np.round(np.matmul(j, inv)) )

    print("\n"*2)






Determinant: 6.0

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]



Determinant: -22.000000000000004

[[ 1. -0. -0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]



Determinant: -271.9999999999999

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



